name: add_to_wallets
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.defuncart.add_to_wallets
        pluginClass: AddToWalletsPlugin
      ios:
        pluginClass: AddToWalletsPlugin
